<?php

namespace Rss\RecommendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RssUrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RssUrlRepository extends EntityRepository
{
}
